version: '3.2'
services:
  pxc1:
    image:
      - percona/percona-xtradb-cluster:5.7.21
    container_name: node1
    ports:
      - "3306:3306"
    volumes:
      - ./volume/pxc/v1:/var/lib/mysql
      - ./volume/pxc/backup:/data
    privileged: true
    networks:
      net1:
        ipv4_address: 172.18.0.2

  pxc2:
    image:
      - percona/percona-xtradb-cluster:5.7.21
    container_name: node2
    ports:
      - "3307:3306"
    volumes:
      - ./volume/pxc/v2:/var/lib/mysql
      - ./volume/pxc/backup:/data
    privileged: true
    depends_on:
      - pxc1
    networks:
      net1:
        ipv4_address: 172.18.0.3

  pxc3:
    image:
      - percona/percona-xtradb-cluster:5.7.21
    container_name: node3
    ports:
      - "3308:3306"
    volumes:
      - ./volume/pxc/v3:/var/lib/mysql
    privileged: true
    depends_on:
      - pxc1
    networks:
      net1:
        ipv4_address: 172.18.0.4

  pxc4:
    image:
      - percona/percona-xtradb-cluster:5.7.21
    container_name: node4
    ports:
      - "3309:3306"
    volumes:
      - ./volume/pxc/v4:/var/lib/mysql
    privileged: true
    depends_on:
      - pxc1
    ipc:
    networks:
      net1:
        ipv4_address: 172.18.0.5

  pxc5:
    image:
      - percona/percona-xtradb-cluster:5.7.21
    container_name: node5
    ports:
      - "3310:3306"
    volumes:
      - ./volume/pxc/v5:/var/lib/mysql
    privileged: true
    depends_on:
      - pxc1
    networks:
      net1:
        ipv4_address: 172.18.0.6

  haproxy1:
    image:
      - haproxy
    container_name: h1
    volumes:
      - ./volume/haproxy/h1:/usr/local/etc/haproxy
    ports:
      - "4001:8888"
      - "4002:3306"
    privileged: true
    depends_on:
      - pxc1
    networks:
      net1:
        ipv4_address: 172.18.0.7
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg

  haproxy2:
    image:
      - haproxy
    container_name: h2
    ports:
      - "4003:8888"
      - "4004:3306"
    volumes:
      - ./volume/haproxy/h2:/usr/local/etc/haproxy
    privileged: true
    networks:
      net1:
        ipv4_address: 172.18.0.8
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg

  redis1:
    image:
      - yyyyttttwwww/redis
    container_name: r1
    ports:
      - "5001:6379"
    privileged: true
    networks:
      net2:
        ipv4_address: 172.19.0.2

  redis2:
    image:
      - yyyyttttwwww/redis
    container_name: r2
    ports:
      - "5002:6379"
    privileged: true
    depends_on:
      - redis1
    networks:
      net2:
        ipv4_address: 172.19.0.3

  redis3:
    image:
      - yyyyttttwwww/redis
    container_name: r3
    ports:
      - "5003:6379"
    privileged: true
    depends_on:
      - redis1
    networks:
      net2:
        ipv4_address: 172.19.0.4

  redis4:
    image:
      - yyyyttttwwww/redis
    container_name: r4
    ports:
      - "5004:6379"
    privileged: true
    depends_on:
      - redis1
    networks:
      net2:
        ipv4_address: 172.19.0.5

  redis5:
    image:
      - yyyyttttwwww/redis
    container_name: r5
    ports:
      - "5005:6379"
    privileged: true
    depends_on:
      - redis1
    networks:
      net2:
        ipv4_address: 172.19.0.6

networks:
  net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
  net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1